# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_BUNDLE "OFF")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_DRAGNDROP "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_PRODUCTBUILD "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BUILD_SOURCE_DIRS "/Users/fresh/Dropbox/htdocs/The-Channel;/Users/fresh/Dropbox/htdocs/The-Channel/build-arm64")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "base")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_BASE_DESCRIPTION "daemon and CLI tools including channeld, chan, and keyd")
set(CPACK_COMPONENT_DEV_DESCRIPTION "headers and libraries for native contract unit testing")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_BASE_FILE_NAME "the-channel_1.0.0-dev1_darwin-amd64.deb")
set(CPACK_DEBIAN_BASE_PACKAGE_NAME "the-channel")
set(CPACK_DEBIAN_BASE_PACKAGE_SECTION "utils")
set(CPACK_DEBIAN_DEV_FILE_NAME "the-channel-dev_1.0.0-dev1_darwin-amd64.deb")
set(CPACK_DEBIAN_DEV_PACKAGE_CONTROL_EXTRA "/Users/fresh/Dropbox/htdocs/The-Channel/build-arm64/scripts/postinst;/Users/fresh/Dropbox/htdocs/The-Channel/build-arm64/scripts/prerm")
set(CPACK_DEBIAN_DEV_PACKAGE_DEPENDS "libgmp-dev, python3-numpy, zlib1g-dev")
set(CPACK_DEBIAN_FILE_NAME "the-channel_1.0.0-dev1_darwin-amd64")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "darwin-amd64")
set(CPACK_DEBIAN_PACKAGE_CONFLICTS "eosio, mandel, leap, spring, vaulta")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "ON")
set(CPACK_DEB_COMPONENT_INSTALL "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/local/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "the-channel built using CMake")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/Users/fresh/Dropbox/htdocs/The-Channel;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/Users/fresh/Dropbox/htdocs/The-Channel/install")
set(CPACK_MODULE_PATH "/Users/fresh/Dropbox/htdocs/The-Channel/CMakeModules")
set(CPACK_NSIS_DISPLAY_NAME "the-channel 1.0.0-dev1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "the-channel 1.0.0-dev1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/Users/fresh/Dropbox/htdocs/The-Channel/build-arm64/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "Tetra Grids")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/local/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "The Channel: the human-first blockchain protocol, derived from Spring 2.0 with Savanna consensus")
set(CPACK_PACKAGE_FILE_NAME "the-channel-1.0.0-dev1-Source")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/TetraGrids/The-Channel")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "the-channel 1.0.0-dev1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "the-channel 1.0.0-dev1")
set(CPACK_PACKAGE_NAME "the-channel")
set(CPACK_PACKAGE_RELOCATABLE "false")
set(CPACK_PACKAGE_VENDOR "Tetra Grids")
set(CPACK_PACKAGE_VERSION "1.0.0-dev1")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_PRODUCTBUILD_DOMAINS "ON")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/local/share/cmake/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/local/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/local/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_CONFLICTS "eosio, mandel, leap, spring, vaulta")
set(CPACK_RPM_PACKAGE_DESCRIPTION "daemon and CLI tools including channeld, chan, and keyd")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "ON")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/Users/fresh/Dropbox/htdocs/The-Channel;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/fresh/Dropbox/htdocs/The-Channel/build-arm64/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "the-channel-1.0.0-dev1-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Darwin")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Darwin-Source")
set(CPACK_WIX_INSTALL_SCOPE "perMachine")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/fresh/Dropbox/htdocs/The-Channel/build-arm64/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
