#!/bin/sh

set -e
Python_SITELIB=$(python3 -c "from sysconfig import get_path; print(get_path('platlib', 'deb_system'))")
mkdir -p $Python_SITELIB
ln -sf /usr/local/share/channel_testing/tests/TestHarness $Python_SITELIB/TestHarness


# channel_testing is part of the package so should already exist by the time postinst runs
if [ ! -L /usr/local/share/channel_testing/bin ]; then
    ln -s ../../bin /usr/local/share/channel_testing/bin
fi
