#!/bin/sh

set -e
Python_SITELIB=$(python3 -c "from sysconfig import get_path; print(get_path('platlib', 'deb_system'))")
mkdir -p $Python_SITELIB
ln -sf /Users/fresh/Dropbox/htdocs/The-Channel/install/share/channel_testing/tests/TestHarness $Python_SITELIB/TestHarness


# channel_testing is part of the package so should already exist by the time postinst runs
if [ ! -L /Users/fresh/Dropbox/htdocs/The-Channel/install/share/channel_testing/bin ]; then
    ln -s ../../bin /Users/fresh/Dropbox/htdocs/The-Channel/install/share/channel_testing/bin
fi
